name: Deploy site to production bucket

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-a39f58809ee2b10f718e995e359b-prodbucket-leu3xiarmbpp
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ur }}
          aws-secret-access-key: ${{ secrets.mum }}
          aws-region: us-east-1
      - name: deploy files to bucket
        run: aws s3 cp ./src/ s3://${{ env.BUCKET_NAME }} --recursive --acl public-read